<?php
/**
 * Ad Copy Generator - Results Display Template
 * 
 * This HTML template displays the generated ad copy results to the user.
 * It presents the AI-generated base text and platform-specific ad copy variations
 * in a clean, organized format for easy review and copying.
 * 
 * Expected Variables (passed from generate_ad_copy.php):
 * - $generated_text: Base ad copy generated by OpenAI GPT-3 API
 * - $google_ad_copy: Google Ads-specific formatted copy with CTA
 * - $facebook_ad_copy: Facebook Ads-specific formatted copy with social CTA
 * - $linkedin_ad_copy: LinkedIn Ads-specific formatted copy with professional CTA
 * 
 * @author AdCopy-Generator
 * @version 1.0.0
 * @requires PHP 7.2+
 * @included_by generate_ad_copy.php
 */
?>
<!DOCTYPE html>
<html>
<head>
    <title>Ad Copy Generator Results</title>
</head>
<body>
    <h1>Ad Copy Generator Results</h1>
    <h2>Generated Text:</h2>
    <p><?php echo $generated_text; ?></p>
    <h2>Google Ads Copy:</h2>
    <p><?php echo $google_ad_copy; ?></p>
    <h2>Facebook Ads Copy:</h2>
    <p><?php echo $facebook_ad_copy; ?></p>
    <h2>LinkedIn Ads Copy:</h2>
    <p><?php echo $linkedin_ad_copy; ?></p>
</body>
</html>
